# Generated by Django 3.0.7 on 2020-06-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareuser',
            name='province',
            field=models.CharField(choices=[('bc', 'British Columbia'), ('ab', 'Alberta'), ('sk', 'Saskachewan'), ('mb', 'Manitoba'), ('on', 'Ontario'), ('qc', 'Quebec'), ('ns', 'Nova Scotia'), ('nb', 'New Brunswick'), ('nl', 'Newfoundland'), ('pe', 'Prince Edward Island'), ('yk', 'Yukon'), ('nt', 'Northwest Territories'), ('nu', 'Nunavut')], default='nu', max_length=25),
        ),
    ]
