# Generated by Django 3.0.7 on 2020-06-24 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_healthcareuser_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcareuser',
            name='language',
        ),
    ]
