# Generated by Django 3.0.7 on 2020-06-30 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_remove_healthcareuser_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthcareProvince",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "abbr",
                    models.SlugField(allow_unicode=True, max_length=2, unique=True),
                ),
            ],
            options={"verbose_name_plural": "provinces", "ordering": ["abbr"]},
        ),
        migrations.AlterField(
            model_name="healthcareuser",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="profiles.HealthcareProvince",
            ),
        ),
    ]
