# Generated by Django 3.0.8 on 2020-07-20 18:31

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_healthcareuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='0', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
