# Generated by Django 3.0.8 on 2020-07-14 19:20

from django.db import migrations, models
import uuid

def create_uuid_for_users(apps, schema_editor):
    User = apps.get_model('profiles', 'HealthcareUser')
    for user in User.objects.all():
        user.id_ = uuid.uuid4()
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_healthcareuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareuser',
            name='id_',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=False, serialize=False, null=True),
        ),
        migrations.RunPython(create_uuid_for_users, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='healthcareuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='healthcareuser',
            name='id_',
            field=models.UUIDField(default=uuid.uuid4, editable=False,
                                   primary_key=True, serialize=False,
                                   null=False),
        ),
        migrations.RenameField(
            model_name='healthcareuser',
            old_name='id_',
            new_name='id',
        ),
    ]
