# Generated by Django 3.0.8 on 2020-07-22 16:31

from django.db import migrations

def create_devices(apps, schema_editor):
    User = apps.get_model('profiles', 'HealthcareUser')
    for user in User.objects.all():
        devices = user.notifysmsdevice_set.all()
        if len(devices) == 0:
            sms_device = user.notifysmsdevice_set.create()
            sms_device.number = user.phone_number.as_e164
            sms_device.save()


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_healthcareuser_phone_number'),
    ]

    operations = [
        migrations.RunPython(create_devices, migrations.RunPython.noop),
    ]
