# Generated by Django 3.1 on 2020-08-31 18:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_healthcareprovince_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareFailedAccessAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Attempt Time')),
                ('username', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='healthcareprovince',
            name='api_key',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Bearer token'),
        ),
    ]
