# Generated by Django 3.1 on 2020-08-27 14:28

from django.db import migrations, models
import uuid


def add_authorized_domains(apps, schema_editor):
    AuthorizedDomain = apps.get_model('profiles', 'AuthorizedDomain')
    domains = [
        'lghealth.ca',
        'easternhealth.ca',
        'centralhealth.nl.ca',
        'westernhealth.nl.ca',
        'nlchi.nl.ca',
        'algomapublichealth.com',
        'bchu.org',
        'chatham-kent.ca',
        'county-lambton.on.ca',
        'durham.ca',
        'eohu.ca',
        'halton.ca',
        'hamilton.ca',
        'healthunit.ca',
        'healthunit.org',
        'hkpr.on.ca',
        'hnhss.ca',
        'hpeph.ca',
        'hpph.ca',
        'kflaph.ca',
        'mlhu.on.ca',
        'niagararegion.ca',
        'norfolkcounty.ca',
        'nwhu.on.ca',
        'ontario.ca',
        'ottawa.ca',
        'peelregion.ca',
        'peterboroughpublichealth.ca',
        'phsd.ca',
        'porcupinehu.on.ca',
        'publichealthgreybruce.on.ca',
        'rcdhu.com',
        'regionofwaterloo.ca',
        'smdhu.org',
        'swpublichealth.ca',
        'tbdhu.com',
        'timiskaminghu.com',
        'toronto.ca',
        'wdgpublichealth.ca',
        'wechu.org',
        'york.ca',
    ]
    for domain in domains:
        try:
            AuthorizedDomain.objects.get(domain=domain)
        except AuthorizedDomain.DoesNotExist:
            AuthorizedDomain.objects.create(domain=domain)


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_healthcareprovince_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='healthcareprovince',
            name='api_key',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Bearer token'),
        ),
        migrations.RunPython(add_authorized_domains, migrations.RunPython.noop),
    ]
