# Generated by Django 3.1 on 2020-09-02 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20200827_1428'),
        ('profiles', '0012_healthcareuser_blocked_until'),
    ]

    operations = [
    ]
