# Generated by Django 3.1 on 2020-09-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_merge_20200902_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcareuser',
            name='blocked_until',
            field=models.DateTimeField(blank=True, help_text='If set, the user will be blocked until that time.', null=True),
        ),
    ]
