# Generated by Django 3.1 on 2020-09-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_merge_20200902_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareuser',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
