# Generated by Django 3.1.2 on 2020-10-29 19:06

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_fix_invitation_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcareuser',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='healthcareuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='You must enter a new security code each time you log in. We’ll text the code to your mobile phone number.', max_length=128, region=None),
        ),
    ]
