# Generated by Django 3.1.5 on 2021-01-19 18:12

from django.db import migrations, models


def add_nitha(apps, schema_editor):
    # We can't import the HealthcareProvince model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Province = apps.get_model("profiles", "HealthcareProvince")
    temp = Province(abbr="NITHA", name="Northern Inter-Tribal Health Authority")
    temp.save()


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0017_update_description_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthcareprovince",
            name="abbr",
            field=models.SlugField(allow_unicode=True, max_length=5, unique=True),
        ),
        migrations.RunPython(add_nitha),
    ]
