# Generated by Django 3.1.7 on 2021-03-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20210215_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareprovince',
            name='qr_code_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
