# Generated by Django 3.2 on 2021-04-07 16:27

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_healthcareprovince_qr_code_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcareuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='You must enter a new code each time you log in. We’ll text the log in code to your mobile phone number.', max_length=128, region=None),
        ),
    ]
