# Generated by Django 3.2.5 on 2021-07-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_alter_healthcareuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareuser',
            name='language_cd',
            field=models.CharField(default='en', max_length=2),
        ),
    ]
