version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=covid_portal
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  web:
    environment:
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DJANGO_ENV=development
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    command: ./entrypoint.sh
    depends_on:
      - db
