# Generated by Django 3.1.7 on 2021-03-25 19:48

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_code', models.CharField(max_length=8, null=True, unique=True, verbose_name='Short code')),
                ('category', models.CharField(max_length=200, verbose_name='Location category')),
                ('category_description', models.CharField(max_length=200, null=True, verbose_name='Location category description')),
                ('name', models.CharField(max_length=200, verbose_name='Location name')),
                ('address', models.CharField(max_length=200, verbose_name='Address line 1')),
                ('address_2', models.CharField(max_length=200, verbose_name='Address line 2')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('province', models.CharField(max_length=100, verbose_name='Province')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal code')),
                ('contact_name', models.CharField(max_length=200, null=True, verbose_name='Name of contact')),
                ('contact_email', models.EmailField(max_length=255, verbose_name='Email address')),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Registrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=200, verbose_name='Full name')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
