# Generated by Django 3.1.7 on 2021-03-31 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrant',
            name='name',
        ),
    ]
