# Generated by Django 3.1.5 on 2021-01-29 21:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=200, verbose_name='Location category')),
                ('name', models.CharField(max_length=200, verbose_name='Location name')),
                ('address', models.CharField(max_length=200, verbose_name='Address line 1')),
                ('address_2', models.CharField(max_length=200, verbose_name='Address line 2')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('province', models.CharField(max_length=100, verbose_name='Province')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal code')),
                ('contact_email', models.EmailField(max_length=255, verbose_name='Email address')),
                ('contact_phone', models.CharField(max_length=255, verbose_name='Contact phone')),
            ],
        ),
    ]
