# Generated by Django 3.1.7 on 2021-04-06 17:56

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_registrant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='contact_phone_ext',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region=None),
        ),
    ]
