# Generated by Django 3.2 on 2021-04-06 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_registrant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='registrant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.registrant'),
        ),
    ]
