# Generated by Django 3.1.6 on 2021-02-04 15:08

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
