# Generated by Django 3.1.6 on 2021-02-15 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_location_short_code'),
        ('register', '0004_emailconfirmation'),
    ]

    operations = [
    ]
