# Generated by Django 3.2.2 on 2021-05-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_location_contact_phone_ext'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Location summary',
                'verbose_name_plural': 'Locations summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('register.location',),
        ),
    ]
