# Generated by Django 3.1.6 on 2021-02-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_location_short_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='short_code',
            field=models.CharField(max_length=8, null=True, unique=True, verbose_name='Short code'),
        ),
    ]
