# Generated by Django 3.1.6 on 2021-02-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_merge_20210215_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='contact_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Contact name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='short_code',
            field=models.CharField(max_length=8, null=True, unique=True, verbose_name='Short code'),
        ),
    ]
