# Generated by Django 3.1.7 on 2021-03-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_location_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='contact_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Name of contact'),
        ),
    ]
