# Generated by Django 3.2.5 on 2021-07-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_survey_emailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='append_registrant_id_ind',
            field=models.BooleanField(default=True, verbose_name='Append registration ID to url'),
        ),
        migrations.AddField(
            model_name='survey',
            name='append_venue_tag_ind',
            field=models.BooleanField(default=True, verbose_name='Append venue tags to url'),
        ),
        migrations.AddField(
            model_name='survey',
            name='registrant_id_url_param',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Registrant ID parameter'),
        ),
        migrations.AddField(
            model_name='survey',
            name='venue_tag_url_param',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Venue tag parameter'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='url',
            field=models.URLField(help_text='Not including any registrant or venue param codes here', verbose_name='General Survey URL'),
        ),
    ]
