# Generated by Django 3.2.4 on 2021-06-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_survey_emailer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('name', 'address', 'address_2', 'city', 'province', 'postal_code')},
        ),
    ]
