# Generated by Django 3.1.7 on 2021-03-24 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20210308_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='category_description',
            field=models.CharField(max_length=200, null=True, verbose_name='Location category description'),
        ),
        migrations.AddField(
            model_name='location',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='registrant',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
