# Generated by Django 3.1.7 on 2021-03-15 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20210308_1515'),
    ]

    operations = [
    ]
