# Generated by Django 3.2.5 on 2021-07-09 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0007_survey_query_params'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareUserSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_ts', models.DateTimeField(blank=True, null=True, verbose_name='Sent Timestamp')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('healthcare_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_recipient', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.survey')),
            ],
        ),
    ]
