# Generated by Django 3.1.7 on 2021-03-18 18:25

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20210318_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 3, 18, 18, 25, 29, 81929, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
