# Generated by Django 3.1.7 on 2021-03-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_merge_20210315_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='category_description',
            field=models.CharField(max_length=200, null=True, verbose_name='Location category description'),
        ),
    ]
