# Generated by Django 3.1.7 on 2021-03-18 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20210318_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailconfirmation',
            old_name='created_at',
            new_name='created',
        ),
    ]
