# Generated by Django 3.1rc1 on 2020-07-27 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('covid_key', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidkey',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='covidkey',
            name='key',
            field=models.BinaryField(),
        ),
    ]
