# Generated by Django 3.1rc1 on 2020-07-28 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid_key', '0002_auto_20200727_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covidkey',
            name='key',
        ),
    ]
