# Generated by Django 3.1.3 on 2020-11-20 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=100, verbose_name='Title in English')),
                ('title_fr', models.CharField(max_length=100, verbose_name='Title in French')),
                ('content_en', models.TextField(blank=True, verbose_name='English Content')),
                ('content_fr', models.TextField(blank=True, verbose_name='French Content')),
                ('display', models.BooleanField(default=False, verbose_name='Show to users')),
                ('level', models.CharField(choices=[('warning', 'Warning'), ('error', 'Error'), ('success', 'Success'), ('info', 'Info')], default='info', max_length=7)),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Creation date')),
                ('site_wide', models.BooleanField(default=False, verbose_name='Site Wide')),
                ('dismissable', models.BooleanField(default=False, verbose_name='Dismissable')),
                ('publish_start', models.DateField(default=datetime.date.today, verbose_name='Publish start date')),
                ('publish_end', models.DateField(blank=True, null=True, verbose_name='Publish end date')),
                ('for_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='For User')),
            ],
        ),
    ]
