# Generated by Django 3.1.4 on 2020-12-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=False, help_text='This must be selected in order for the announcement to be displayed to users', verbose_name='Announcement active'),
        ),
    ]
