# Generated by Django 3.1.4 on 2020-12-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ga_code', models.CharField(blank=True, default=None, help_text='If no tracking code provided Google Analytics will not record any data for site.', max_length=100, null=True, verbose_name='Google Analytics Code')),
            ],
            options={
                'verbose_name': 'Google Analytics V4 Tracking Code',
            },
        ),
    ]
