# Generated by Django 3.2.1 on 2021-05-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_analytics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleAnalytics',
        ),
    ]
