# Generated by Django 3.1.7 on 2021-03-25 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3')], editable=False, max_length=1)),
                ('start_date', models.DateTimeField(editable=False)),
                ('end_date', models.DateTimeField(editable=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='register.location')),
            ],
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['start_date'], name='outbreaks_n_start_d_95cef2_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['end_date'], name='outbreaks_n_end_dat_b30c2d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('start_date', 'end_date', 'location')},
        ),
    ]
