# Generated by Django 3.1.7 on 2021-03-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbreaks', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('start_date', 'end_date', 'location')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['start_date'], name='outbreaks_n_start_d_95cef2_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['end_date'], name='outbreaks_n_end_dat_b30c2d_idx'),
        ),
    ]
