# Generated by Django 3.2.2 on 2021-05-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outbreaks', '0002_auto_20210430_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Notification summary',
                'verbose_name_plural': 'Notifications summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('outbreaks.notification',),
        ),
    ]
