# Generated by Django 3.1.6 on 2021-02-18 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0005_auto_20210215_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], editable=False, max_length=1)),
                ('start_date', models.DateTimeField(editable=False)),
                ('end_date', models.DateTimeField(editable=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='register.location')),
            ],
        ),
    ]
