name: Staging — Push container to ECR

on:
  push:
    branches: [main]

env:
  GITHUB_SHA: ${{ github.sha }}
  ECR_REGISTRY: ${{ steps.login-ecr-covid-portal.outputs.registry }}
  ECR_REPOSITORY: covid-alert-portal-terraform

jobs:
  push-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for container to build
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-container-staging
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: build-container
          ref: ${{ github.sha }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Read VERSION file
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./VERSION

      - name: Build Covid Portal
        run: docker build -t base --build-arg GITHUB_SHA_ARG=$GITHUB_SHA .

      - name: Configure Staging AWS credentials
        id: aws-covid-portal
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Login to Staging Amazon ECR
        id: login-ecr-covid-portal
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag Images for Staging
        env:
          VERSION: ${{ steps.version.outputs.content }}
        run: |
          docker tag base $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA
          docker tag base $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION
          docker tag base $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Push containers to Staging Amazon ECR
        env:
          VERSION: ${{ steps.version.outputs.content }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Logout of Staging Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr-covid-portal.outputs.registry }}
