name: Terraform Security scan
on:
  push:
    branches: [aws_docker_build]

jobs:
  terraform-security-scan:
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Terraform security scan
        uses: triat/terraform-security-scan@v1.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}